### ISSUE TITLE
Uniforme

### ISSUE THREAD

**Issue by ToasterBR** [aegisarma3/ASIN#20]
Camisa tática e combinação de cor

![image](https://cloud.githubusercontent.com/assets/4144587/8422029/ad84acec-1eac-11e5-933b-26a8b763d7f8.png)

**Comment by Odisii** [comment]
Positivo

**Comment by Collumbus** [comment]
+1

**Comment by JotaAegis** [comment]
+1

**Comment by ArthurLM1** [comment]
+1

**Comment by ToasterBR** [comment]
Done
